springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8083
  # Context path: gestion-stock/api
  servlet:
    context-path: /gestion-stock/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/adminapp-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    path: ./logs
    name: logs.log
